openapi: 3.0.0
info:
  title: API Dokument für die Timekeeper Demo App
  version: 1.0
servers:
  - url: https://api.server.test/v1
paths:
  /zeiten:
    get:
      description: gibt alle erfassten Zeiten zurück
      responses:
        '200':
          description: OK
